SECRETARIAS = [
    "Selecione...","CIDADANIA", "COMUNICAÇÃO", "CONTROLE INTERNO",
    "CULTURA E ESPORTES", "DESENVOLVIMENTO ECONÔMICO", "EDUCAÇÃO",
    "FAZENDA", "FORÇA POLICIAL", "GOVERNO", "INFRAESTRUTURA", "OUTROS",
    "PROCURADORIA", "SAÚDE", "SEGURANÇA", "SUSTENTABILIDADE"
]

TECNICOS = [
    "Selecione...", "ABIMADÉSIO", "ANTONY CAUÃ", "DIEGO CARDOSO",
    "DIEL BATISTA", "JOSAFÁ MEDEIROS", "MAYKON RODOLFO", "ROMÉRIO CIRQUEIRA",
    "VALMIR FRANCISCO"
]

CATEGORIAS_INTERNA = [
    "Selecione...", "CFTV", "COMPUTADORES", "IMPRESSORAS", "OUTROS",
    "REDES", "SISTEMAS", "TELEFONIA"
]

CATEGORIAS_EXTERNA = [
    "Selecione...", "CONFIGURAÇÃO", "INSTALAÇÃO", "MANUTENÇÃO",
    "OUTROS", "REDES"
]

EQUIPAMENTOS = [
    "Selecione...", "CAMERA", "CELULAR", "COMPUTADOR", "IMPRESSORA",
    "MONITOR", "NOBREAK", "NOTEBOOK", "PERIFÉRICO", "TABLET", "TRANSFORMADOR",
    "ROTEADOR", "SISTEMA", "SOFTWARE"
]

STATUS_OPTIONS = [
    "Todos", "EM ABERTO", "AGUARDANDO PEÇA(S)", "FINALIZADO", "AGUARDANDO RETIRADA", "ENTREGUE AO CLIENTE"
]
